### ISSUE TITLE
Error in Collector Install 

### ISSUE THREAD

**Issue by kariboe** [logicmonitor/logicmonitor-puppet-v4#20]
Is it possible that something changed in the LM API? We are receiving this error for 2 days now, before no problem at all. 

Debug: Collector[XXX](provider=collector): Checking if Collector exists with description "XXX"
Error: /Stage[main]/Logicmonitor::Install/Collector[XXX]: Could not evaluate: no implicit conversion of nil into String

Collector exist in LM, so no problem there. 

Kind Regards,

Stefaan

**Comment by skt44** [comment]
Hi @kariboe 

We're looking into this, but haven't been able to identify the issue - the API to get a Collector based on description seems to be working okay. We'll add more logging with #21, which should better enable us to identify why the requests are failing in your case.

Thanks,
Sarah

**Comment by skt44** [comment]
@kariboe - can you upgrade to the [latest version of the module](https://forge.puppet.com/logicmonitor/logicmonitor)? The additional logging should help shed light on what's causing this issue. Thanks!

**Comment by kariboe** [comment]
Upgraded to the lastest code, run Puppet agent on the collector, but no additional logging is seen. So apparently no issues with the LM API. 

I only do this in my puppet code: 

```
    class {'::logicmonitor::master':
      account     => $logicmonitor_master_software_account,
      access_id   => $logicmonitor_master_software_access_id,
      access_key  => $logicmonitor_master_software_access_key,
    }

    class {'::logicmonitor::collector':}
```

Maybe that is not enough?

**Comment by kariboe** [comment]
Getting this as output now, its worse now :-) 

Alert: Device[XXX](provider=device): Request Failed. http_method: GET, scheme: https, host: xxx.logicmonitor.com, path: /santaba/rest/device/devices, query: filter=displayName%XXX&fields=id&size=1, data: 
Error: /Stage[main]/Logicmonitor::Device/Device[XXX]: Could not evaluate: comparison of String with 200 failed
Error: /Stage[main]/Logicmonitor::Install/Collector[XXX]: Could not evaluate: no implicit conversion of nil into String

**Comment by skt44** [comment]
@kariboe we found the issue, and fixed it with #23. A new version is [available on Puppet Forge](https://forge.puppet.com/logicmonitor/logicmonitor).

**Comment by kariboe** [comment]
Updated to the latest version and we have the original error again:

Error: /Stage[main]/Logicmonitor::Install/Collector[XXX]: Could not evaluate: no implicit conversion of nil into String

So, no issue with the LM API I guess. Strange this is we don't have to provide any arguments/variables when including the following code:  

`class {'::logicmonitor::collector':}
`

**Comment by skt44** [comment]
@kariboe can you do a puppet run with the debug flag and post the output? We'll need a big more context to dig into this further. Thanks!

**Comment by ngeorgieff** [comment]
I'm having the same issue:

`Debug: Collector[server-lm-chs-p01.dc.corp](provider=collector): Checking if Collector exists with description "server-lm-chs-p01.dc.corp"
Error: /Stage[main]/Logicmonitor::Install/Collector[server-lm-chs-p01.dc.corp]: Could not evaluate: no implicit conversion of nil into String
Notice: /Stage[main]/Logicmonitor::Install/Collector_installer[server-lm-chs-p01.dc.corp]: Dependency Collector[server-lm-chs-p01.dc.corp] has failures: true
Warning: /Stage[main]/Logicmonitor::Install/Collector_installer[server-lm-chs-p01.dc.corp]: Skipping because of failed dependencies
Debug: /Stage[main]/Logicmonitor::Install/Collector_installer[server-lm-chs-p01.dc.corp]: Resource is being skipped, unscheduling all events
Debug: Class[Logicmonitor::Install]: Resource is being skipped, unscheduling all events
Notice: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-agent]: Dependency Collector[server-lm-chs-p01.dc.corp] has failures: true
Warning: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-agent]: Skipping because of failed dependencies
Debug: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-agent]: Resource is being skipped, unscheduling all events
Notice: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-watchdog]: Dependency Collector[server-lm-chs-p01.dc.corp] has failures: true
Warning: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-watchdog]: Skipping because of failed dependencies
Debug: /Stage[main]/Logicmonitor::Service/Service[logicmonitor-watchdog]: Resource is being skipped, unscheduling all events
Debug: Class[Logicmonitor::Service]: Resource is being skipped, unscheduling all events
Debug: Class[Logicmonitor::Collector]: Resource is being skipped, unscheduling all events
Debug: Prefetching device_group resources for device_group
Debug: Device_group[/Development](provider=device_group): Checking if device group "Development" exists
Debug: Device_group[/Development](provider=device_group): {"id"=>136, "parentId"=>1, "name"=>"Development", "description"=>"This is the top level puppet managed device group", "groupType"=>"Normal", "awsRegionsInfo"=>"", "azureRegionsInfo"=>"", "awsTestResult"=>nil, "azureTestResult"=>nil, "autoVisualResult"=>nil, "awsTestResultCode"=>200, "azureTestResultCode"=>200, "createdOn"=>1539706786, "disableAlerting"=>false, "enableNetflow"=>true, "hasNetflowEnabledDevices"=>false, "appliesTo"=>"", "customProperties"=>[], "fullPath"=>"Development", "numOfHosts"=>0, "numOfAWSDevices"=>0, "numOfAzureDevices"=>0, "numOfDirectDevices"=>0, "numOfDirectSubGroups"=>0, "effectiveAlertEnabled"=>true, "sdtStatus"=>"none-none-none", "alertStatus"=>"none", "alertStatusPriority"=>100000, "clusterAlertStatus"=>"none", "clusterAlertStatusPriority"=>100000, "alertDisableStatus"=>"none-none-none", "alertingDisabledOn"=>nil, "groupStatus"=>"normal", "userPermission"=>"write", "extra"=>{}, "subGroups"=>[], "defaultCollectorId"=>0, "defaultCollectorDescription"=>nil}
Debug: Device_group[/Development](provider=device_group): Finished in 77.99696 ms
Debug: Device_group[/Development](provider=device_group): Checking description for device group: "Development"
Debug: Device_group[/Development](provider=device_group): Finished in 80.390181 ms
`

**Comment by skt44** [comment]
Thanks for the additional detail @ngeorgieff - we'll look into it

**Comment by skt44** [comment]
Hi @ngeorgieff we're currently troubleshooting, and should have an update soon!

**Comment by pyang55** [comment]
@kariboe @ngeorgieff can you please try

    class {'::logicmonitor':
      account     => $logicmonitor_master_software_account,
      access_id   => $logicmonitor_master_software_access_id,
      access_key  => $logicmonitor_master_software_access_key,
    }

    class {'::logicmonitor::collector':}

**Comment by skt44** [comment]
@ngeorgieff @kariboe we think this issue is a result of setting the LM API information for the logicmonitor::master class instead of the top level logicmonitor class. The credentials need to be set at the top level class so that they can be inherited by all child classes, like this:

    class {'logicmonitor':
      account     => $logicmonitor_master_software_account,
      access_id   => $logicmonitor_master_software_access_id,
      access_key  => $logicmonitor_master_software_access_key,
    }

**Comment by skt44** [comment]
@kariboe @ngeorgieff with this module, the API credentials have to be set for the top level logicmonitor class, not the logicmonitor::master class, and the child classes all inherit credentials from the top level class.

**Comment by ngeorgieff** [comment]
Thank you! works now
