### ISSUE TITLE
Problems adding devices

### ISSUE THREAD

**Issue by kellyzdude** [logicmonitor/logicmonitor-puppet-v4#5]
Hello,

I've been using the previous version of the Logicmonitor module (v1.0.2, which never worked "perfectly", but better than currently). Circumstances have changed and forced an upgrade to 2.0.2.

Collectors are able to add themselves without error, which tells me that the API interaction is working correctly, however, when trying to add device blocks to that the collectors and other systems in our environment can add themselves, we run into issues.

Full output is here, for one device:

[output.txt](https://github.com/logicmonitor/logicmonitor-puppet-v4/files/1260143/output.txt)

Non-trace, non-debug version:
```
Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass
Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass
Wrapped exception:
undefined method `[]' for nil:NilClass
Error: /Stage[main]/Logicmonitor::Master/Device[(removed).186]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass`
```

I've tried this with logicmonitor::master configured against the Puppet Master, which is running:
```
[root@puppetmaster ~]# puppet --version
4.10.4
```

And against the collectors, which are running:
```
[root@collect ~]# puppet --version
3.8.7
```

Both agents give the same negative result.

The devices are being created by this code:
```
        $logmon_base = "/00_(removed)/Linux Servers/${location}"

        class {'logicmonitor::device':
                collector=> "${location}collect.corp.example.com",
                hostname => "${ipaddress}",
                display_name  => "${fqdn}",
                groups   => ["$logmon_base"],
        }
```

$location is a valid fact, calculated based on private IP ranges assigned to each of our locations. Our collectors are properly listed with their FQDN as the description, which should match each collector=> line.

Also, as a side note, every run seems to go through the process of identifying the group tree as missing (which it isn't) and creating it (fortunately not duplicating it). I've tried without the leading "/" and the same result.

I'd be grateful for any assistance. I hope I'm just doing something wrong, but it would appear that the module is not functioning as documented.

**Comment by Skarzee** [comment]
HI @kellyzdude and Logicmonitor Team

Happy that I am not the only one running into problems. In some freak coincidence I also had a look at getting this working today with our Puppet estate on a sandbox account. As you said, the Collector/Master registers itself without issues. There are issues however when adding other devices.

We also are running Puppet 3.7 on our collectors:

`[Tue Aug 29 18:19:14] [root@lm-collector-01.dqs ~]# puppet --version
3.7.3`

`Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass at 91:/etc/puppet/environments/PSM3562/modules/logicmonitor/manifests/device.pp
Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass at 91:/etc/puppet/environments/PSM3562/modules/logicmonitor/manifests/device.pp
Wrapped exception:
undefined method `[]' for nil:NilClass
Error: /Stage[main]/Logicmonitor::Device/Device[lm-collector-01.dqs.traveljigsaw.com]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass at 91:/etc/puppet/environments/PSM3562/modules/logicmonitor/manifests/device.pp
Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass
Error: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass
Wrapped exception:
undefined method `[]' for nil:NilClass
Error: /Stage[main]/Logicmonitor::Master/Device[watdev-01.dqs.traveljigsaw.com]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `[]' for nil:NilClass`

I am trying to add the collector to a group as per documentation like so:

 `class { 'logicmonitor::device':
    collector    => $::fqdn,
    groups       => ['/Gatherers', '/DQS'],
    hostname     => $::fqdn,
    display_name => $::fqdn,
    description  => 'Node specified description',
  }`

However, this yields the above error. 

> Also, as a side note, every run seems to go through the process of identifying the group tree as missing (which it isn't) and creating it (fortunately not duplicating it). I've tried without the leading "/" and the same result.

I am also seeing this behaviour when I am creating groups from this module currently

* I will attempt to manually define some of the variables in the module to see if it's a parsing issue, as hostname is currently defined as:
** Note these should already be populated by FQDN which is available via facter

**Facter:**
[Tue Aug 29 18:27:18] [root@lm-collector-01.dqs ~]# facter | grep fqdn
fqdn => lm-collector-01.dqs.traveljigsaw.com

`class logicmonitor::device(
 $collector        = $::fqdn,
  $hostname         = $::fqdn,
  $display_name     = $::fqdn,
  $description      = '',
  $disable_alerting = false,
  $groups           = [],
  $properties       = {},
)

# Create Resource
  @@device { $hostname:
    ensure           => present,
    collector        => $collector,
    display_name     => $display_name,
    description      => $description,
    disable_alerting => $disable_alerting,
    groups           => $groups,
    properties       => $properties,
` }

* Because of this, I am wondering if it is possible to just define a node with a exported resource, just like is done via the current **device_group** class. I will report back if so!

Please let us both know if there's any input from you guys about these issues. Thanks.

**Comment by ethanculler** [comment]
Thanks for sending this in @kellyzdude and @Skarzee. We are currently investigating and will update with more information shortly.

**Comment by ethanculler** [comment]
@kellyzdude and @Skarzee sorry for the delay. This was a little more involved to track down than was expected. You guys have identified a bug with the way device groups are handled within the context of a device.

As you noted, it looks like it continues to try and create the full path of groups each time. Unfortunately it's a little worse than that. Since the bug involves looking up existing groups it will end up creating the child groups at the root level on subsequent runs.

This is also the reason that the device is unable to be added correctly. Since it is unable to detect the set of groups which it should be a member of, it can't build the necessary host metadata and you get the "no such method" error.

#6 should resolve this issue.

The following node definition had the same issue that you were experiencing when running against master:

`node /host.*/ {
        class {'logicmonitor::device':
                collector    => 'test',
                groups       => ['00_(removed)/Linux Servers/test', 'no/special/characters'],
        }
}
`

this same definition succeeded, but will still require additional testing before it will be merged into master.

**Comment by ethanculler** [comment]
Oops, closed a bit too soon.

**Comment by Skarzee** [comment]
Thanks for looking into this @ethanculler - will be pulling it down shortly to test!
